// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

function buildDatabaseUrl() {
  return `mysql://${env("DB_USER")}:${env("DB_PASS")}@${env("DB_HOST")}:${env("DB_PORT")}/${env("DB_NAME")}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
